# Generated by Django 4.0.6 on 2022-07-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='кщду',
            field=models.CharField(choices=[('hr', 'hr'), ('employee', 'employee'), ('unknown', 'unknown')], default='unknown', max_length=8),
        ),
    ]
